#!/bin/sh

rnd=`cat /dev/urandom | tr -dc 'A-Z' | head -c1`
model_hardware=$(cat /proc/cpuinfo | grep 'machine' | cut -f2 -d ":" | cut -b 10-50 | tr ' ' '_')

###Sync
uci -q get wifimedia.@sync[0] || {
	uci batch <<-EOF
	add wifimedia sync
	set wifimedia.@sync[0]=sync
	set wifimedia.@sync[0].version=2.1.0
	#set wifimedia.@sync[0].domain="crm.wifimedia.com.vn"
	set wifimedia.@sync[0].server="http://monitor.wifimedia.vn/api/monitoring/"
	commit wifimedia
EOF
}

###Build Date
uci -q get wifimedia.@builddate[0] || {
	uci batch <<-EOF
	add wifimedia builddate
	set wifimedia.@builddate[0]=builddate
	set wifimedia.@builddate[0].date=01/06/2020
	commit wifimedia
EOF
}

uci -q get wifimedia.@switchmode[0] || {
	uci batch <<-EOF
	add wifimedia switchmode
	set wifimedia.@switchmode[0].switch_port=0
	commit wifimedia
EOF
}

uci -q get wifimedia.@wireless[0] || {
	uci batch <<-EOF
	add wifimedia wireless
	set wifimedia.@wireless[0]=wireless
	commit wifimedia
EOF
}

uci -q get wifimedia.@hash256[0] || {
	uci batch <<-EOF
	add wifimedia hash256
	set wifimedia.@hash256[0]=hash256
	commit wifimedia
EOF
}

uci -q get wifimedia.@heartbeat[0] || {
        uci batch <<EOF
        add wifimedia heartbeat
		#set wifimedia.@heartbeat[0].uri="http://api.nextify.vn/clients_around"
		#set wifimedia.@heartbeat[0].heartbeat_uri="http://portal.nextify.vn/heartbeat"
        commit wifimedia
EOF
}

uci batch <<-EOF
	set system.@system[0]=system
	set system.@system[0].hostname="VSTV.VN"
	set system.@system[0].zonename='Asia/Ho Chi Minh'
	set system.@system[0].timezone=ICT-7
EOF

if  [ "$model_hardware" == "TL-WR940N_v6" ] ;then
	uci batch <<-EOF
		set	network.lan.type='bridge'
		set	network.lan.ifname='eth1.1'
		set	network.lan.proto='static'
		set	network.lan.ipaddr='192.168.173.225'
		set	network.lan.netmask='255.255.255.248'
		set	network.lan.gateway='192.168.173.1'
		set	network.lan.dns='192.168.173.199 192.168.177.199 192.168.172.199'
		set	network.wan=interface
		set	network.wan.ifname='eth0'
		set	network.wan.proto='dhcp'
		set	network.wan.type='bridge'
		set	network.wwan=interface
		set	network.wwan.proto='dhcp'
		set	dhcp.lan=dhcp
		set	dhcp.lan.interface='lan'
		set	dhcp.lan.force='1'
		set	dhcp.lan.start='225'
		set	dhcp.lan.leasetime='1h'
		set	dhcp.lan.netmask='255.255.255.248'
		set	dhcp.lan.dhcp_option='6,192.168.172.199,192.168.177.199'
		commit
	EOF

	uci batch <<-EOF
		set wireless.radio0=wifi-device
		set wireless.radio0.type='mac80211'
		set wireless.radio0.channel='11'
		set wireless.radio0.hwmode='11g'
		set wireless.radio0.htmode='HT20'
		set wireless.radio0.disabled='0'
		set wireless.radio0.macaddr='10:27:f5:c5:a2:b7'
		set wireless.radio0.country='US'
		set wireless.radio0.txpower='22'
		set wireless.radio0.legacy_rates='1'
		set wireless.radio0.mu_beamformer='0'
		set wireless.default_radio0=wifi-iface
		set wireless.default_radio0.device='radio0'
		set wireless.default_radio0.network='lan'
		set wireless.default_radio0.mode='ap'
		set wireless.default_radio0.encryption='none'
		set wireless.default_radio0.maxassoc='30'
		set wireless.default_radio0.ssid='WIFIVSTV.VN'
		add wireless wifi-iface
		set wireless.@wifi-iface[1]=wifi-iface
		set wireless.@wifi-iface[1].ssid='VSTV_Wireless'
		set wireless.@wifi-iface[1].encryption='none'
		set wireless.@wifi-iface[1].device='radio0'
		set wireless.@wifi-iface[1].mode='sta'
		set wireless.@wifi-iface[1].network='wwan'
		set wireless.@wifi-iface[1].bssid='F0:9C:E9:F0:0C:94'
		set firewall.@zone[1].network='wan wwan'
		commit wireless
	EOF

fi

if [ "$model_hardware" == "TL-WR940N_v6" ];then
	echo "TL-WR940N v6.1" >/etc/hardware
fi

uci batch <<-EOF
	delete network.wan6
	commit network
EOF

uci batch <<-EOF
	set firewall.@zone[1].input="ACCEPT"
	commit firewall
	EOF
#NET_ID="wan wwan"
#FW_ZONE="hotspot"
#IFNAME="eth0.300" #VLAN1
#uci batch << EOF
	set firewall.${FW_ZONE}=zone
	set firewall.${FW_ZONE}.name=${FW_ZONE}
	set firewall.${FW_ZONE}.network=${NET_ID}
	set firewall.${FW_ZONE}.forward=ACCEPT
	set firewall.${FW_ZONE}.output=ACCEPT
	set firewall.${FW_ZONE}.input=ACCEPT 
	set firewall.${FW_ZONE}_fwd=forwarding
	set firewall.${FW_ZONE}_fwd.src=${FW_ZONE}
	set firewall.${FW_ZONE}_fwd.dest=wan
	set firewall.${FW_ZONE}_dhcp=rule
	set firewall.${FW_ZONE}_dhcp.name=${FW_ZONE}_DHCP
	set firewall.${FW_ZONE}_dhcp.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dhcp.target=ACCEPT
	set firewall.${FW_ZONE}_dhcp.proto=udp
	set firewall.${FW_ZONE}_dhcp.dest_port=67-68
	set firewall.${FW_ZONE}_dns=rule
	set firewall.${FW_ZONE}_dns.name=${FW_ZONE}_DNS
	set firewall.${FW_ZONE}_dns.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dns.target=ACCEPT
	set firewall.${FW_ZONE}_dns.proto=tcpudp
	set firewall.${FW_ZONE}_dns.dest_port=53
	commit firewall
	commit network
	commit dhcp
#EOF
		
#Password	
echo -e "admin:x:1000:1000:admin:/root:/bin/false" >>/etc/passwd
echo -e "admin:*:0:0:99999:7:::" >>/etc/shadow
echo -e "wifimedia\nwifimedia" | passwd admin

echo -e "wifimedia:x:0:0:wifimedia:/root:/bin/ash" >>/etc/passwd
echo -e "wifimedia:*:0:0:99999:7:::" >>/etc/shadow
echo -e "09465670089\n09465670089" | passwd wifimedia

#Change password for root
word=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  10,11,13,14,16,17 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
pwd=$(echo -n $word | md5sum | awk '{print $1}')
#echo -e "$pwd\n$pwd" | passwd root
echo -e "wifimedia\nwifimedia" | passwd root
#End

#Cron heartbeat
echo '*/2 * * * * /sbin/wifimedia/controller.sh srv' >/etc/crontabs/root  #monitor
echo '* * * * * /sbin/wifimedia/controller.sh checking' >>/etc/crontabs/root
#Info
CODENAME="wifimedia"
if [ -f "/etc/codename" ]; then
	source /etc/codename
fi
uci batch <<-EOF
	delete wifimedia.Version
	set wifimedia.Version=version
	set wifimedia.Version.ver=$CODENAME
	commit wifimedia
EOF

source /etc/openwrt_release
rm -f /etc/openwrt_release
DISTRIB_DESCRIPTION=$(uci get wifimedia.Version.ver)""
echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
echo 'DISTRIB_REVISION="'" "'"' >> /etc/openwrt_release
echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release

#uci set dhcp.lan.start=99
#uci set dhcp.lan.limit=100
#uci set dhcp.lan.leasetime=1h
#uci commit dhcp
#SYNCH TIME
uci batch <<-EOF
	del system.ntp
	set system.ntp=timeserver
        add_list system.ntp.server='0.asia.pool.ntp.org'
        add_list system.ntp.server='1.asia.pool.ntp.org'
        add_list system.ntp.server='2.asia.pool.ntp.org'
        add_list system.ntp.server='3.asia.pool.ntp.org'
	set system.ntp.enabled=1
	set system.ntp.enable_server=1
	commit system
EOF
/etc/init.d/sysntpd start >/dev/null
uci set luci.diag.dns="google.com.vn"
uci set luci.diag.ping="google.com.vn"
uci set luci.diag.route="google.com.vn"

#Change ssh
uci batch <<-EOF
	set dropbear.@dropbear[0].Port=2702
	commit dropbear
EOF


uci -q get wifimedia.MeshPoint || {
	uci batch <<-EOF
	set wifimedia.MeshPoint=mesh
	set wifimedia.MeshPoint.enable=0
	commit
	EOF
}

touch /etc/opt/wfm_status
rm -f /etc/banner
mv /etc/banner_ /etc/banner
chmod +x /sbin/wifimedia/*
/etc/init.d/system reload
/etc/init.d/led reload
/etc/init.d/cron restart
/etc/init.d/cron enable
/etc/init.d/network_reload enable
/etc/init.d/network restart
ifup wan
