#!/bin/sh

rnd=`cat /dev/urandom | tr -dc 'A-Z' | head -c1`
model_hardware=$(cat /proc/cpuinfo | grep 'machine' | cut -f2 -d ":" | cut -b 10-50 | tr ' ' '_')
newifi3=$(cat /proc/cpuinfo | grep 'machine' | cut -f2 -d ":" | awk '{print $1}')
###Sync
uci -q get wifimedia.@sync[0] || {
	uci batch <<-EOF
	add wifimedia sync
	set wifimedia.@sync[0]=sync
	set wifimedia.@sync[0].version=2.1.0
	#set wifimedia.@sync[0].domain="crm.wifimedia.com.vn"
	set wifimedia.@sync[0].server="http://monitor.wifimedia.vn/api/monitoring/"
	commit wifimedia
EOF
}

###Build Date
uci -q get wifimedia.@builddate[0] || {
	uci batch <<-EOF
	add wifimedia builddate
	set wifimedia.@builddate[0]=builddate
	set wifimedia.@builddate[0].date=14/01/2020
	commit wifimedia
EOF
}

uci -q get wifimedia.@switchmode[0] || {
	uci batch <<-EOF
	add wifimedia switchmode
	set wifimedia.@switchmode[0].switch_port=0
	commit wifimedia
EOF
}

uci -q get wifimedia.@wireless[0] || {
	uci batch <<-EOF
	add wifimedia wireless
	set wifimedia.@wireless[0]=wireless
	commit wifimedia
EOF
}

uci -q get wifimedia.@hash256[0] || {
	uci batch <<-EOF
	add wifimedia hash256
	set wifimedia.@hash256[0]=hash256
	commit wifimedia
EOF
}

uci -q get wifimedia.@LTE[0] || {
	uci batch <<-EOF
	add wifimedia LTE
	set wifimedia.@LTE[0]=lte
	set wifimedia.@LTE[0].lte=0
	commit wifimedia
EOF
}
#change ver  for upgrade
uci set wifimedia.@sync[0].version=2.1.1
uci set wifimedia.@sync[0].rsn=2.6
uci set wifimedia.@sync[0].sw=2.5
uci set wifimedia.@sync[0].button=2.4
uci set wifimedia.@sync[0].ftrs=2.3
uci set wifimedia.@sync[0].passwdwifi=2.2
uci set wifimedia.@sync[0].passwd=2.1
uci set wifimedia.@advance[0].wireless_cfg=0
uci commit wifimedia

uci batch <<-EOF
	set system.@system[0]=system
	set system.@system[0].hostname="WIFIMEDIA"
	set system.@system[0].zonename='Asia/Ho Chi Minh'
	set system.@system[0].timezone=ICT-7
EOF


if [ "$newifi3" == "Newifi-D2" ];then
	uci batch <<-EOF
		set network.lan.ipaddr=172.16.99.1
		set network.wan.type=bridge
		delete network.globals
		set dhcp.lan.force=1
		set dhcp.lan.netmask=255.255.255.0
		add_list dhcp.lan.dhcp_option=6,8.8.8.8,8.8.4.4
		commit
	EOF

	uci batch <<-EOF
	#5G
		set wireless.radio1.channel=157
		set wireless.radio1.htmode=VHT40
		set wireless.default_radio1.ssid="WIFIMEDIA.VN"
		set wireless.radio0.country="US"
		set wireless.radio1.txpower=25
	#2.4G
		set wireless.radio0.macaddr=$(cat /sys/class/ieee80211/phy0/macaddress)
		add_list wireless.radio0.ht_capab="SHORT-GI-20"
		add_list wireless.radio0.ht_capab="SHORT-GI-40"
		add_list wireless.radio0.ht_capab="RX-STBC1"
		add_list wireless.radio0.ht_capab="DSSS_CCK-40"
		set wireless.radio0.country="US"
		set wireless.radio0.txpower=29
		set wireless.radio0.channel=auto
		set wireless.default_radio0.ssid="WIFIMEDIA.VN"
		#set wireless.default_radio0.macaddr=40:A5:EF:63:E7:6D
		#set wireless.default_radio0.ssid=PDA_$rnd
		#set wireless.default_radio0.encryption="psk2"
		#set wireless.default_radio0.key="123456A@$rnd"
		set wireless.default_radio0.maxassoc=30	
		commit wireless
	EOF
	echo "NEWIFI" >/etc/hardware
fi

#enable wifi
uci set wireless.radio0.disabled="0"
uci commit wireless
wifi
#for hwmode n ac
uci batch <<-EOF
	delete network.wan6
	commit network
EOF

uci batch <<-EOF
	set firewall.@zone[1].input="ACCEPT"
	commit firewall
	EOF
		
#Password	
echo -e "admin:x:1000:1000:admin:/root:/bin/false" >>/etc/passwd
echo -e "admin:*:0:0:99999:7:::" >>/etc/shadow
echo -e "wifimedia\nwifimedia" | passwd admin

echo -e "wifimedia:x:0:0:wifimedia:/root:/bin/ash" >>/etc/passwd
echo -e "wifimedia:*:0:0:99999:7:::" >>/etc/shadow
echo -e "09465670089\n09465670089" | passwd wifimedia

#Change password for root
word=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  10,11,13,14,16,17 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
pwd=$(echo -n $word | md5sum | awk '{print $1}')
#echo -e "$pwd\n$pwd" | passwd root
echo -e "wifimedia\nwifimedia" | passwd root
#End

#Cron heartbeat
echo '* * * * * /sbin/wifimedia/controller.sh srv' >/etc/crontabs/root  #monitor
echo '* * * * * /sbin/wifimedia/controller.sh checking' >>/etc/crontabs/root
#Info
CODENAME="wifimedia"
if [ -f "/etc/codename" ]; then
	source /etc/codename
fi
uci batch <<-EOF
	delete wifimedia.Version
	set wifimedia.Version=version
	set wifimedia.Version.ver=$CODENAME
	commit wifimedia
EOF

source /etc/openwrt_release
rm -f /etc/openwrt_release
DISTRIB_DESCRIPTION=$(uci get wifimedia.Version.ver)""
echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
echo 'DISTRIB_REVISION="'" "'"' >> /etc/openwrt_release
echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release


uci set dhcp.lan.start=99
uci set dhcp.lan.limit=100
uci set dhcp.lan.leasetime=1h
uci commit dhcp
#SYNCH TIME
uci batch <<-EOF
	del system.ntp
	set system.ntp=timeserver
        add_list system.ntp.server='0.asia.pool.ntp.org'
        add_list system.ntp.server='1.asia.pool.ntp.org'
        add_list system.ntp.server='2.asia.pool.ntp.org'
        add_list system.ntp.server='3.asia.pool.ntp.org'
	set system.ntp.enabled=1
	set system.ntp.enable_server=1
	commit system
EOF
/etc/init.d/sysntpd start >/dev/null
uci set luci.diag.dns="google.com.vn"
uci set luci.diag.ping="google.com.vn"
uci set luci.diag.route="google.com.vn"

#Change ssh
uci batch <<-EOF
	set dropbear.@dropbear[0].Port=2702
	commit dropbear
EOF

###Sync
uci -q get wifimedia.@sync[0] || {
	uci batch <<-EOF
	add wifimedia sync
	set wifimedia.@sync[0]=sync
	set wifimedia.@sync[0].version=2.1.0
	#set wifimedia.@sync[0].domain="crm.wifimedia.com.vn"
	set wifimedia.@sync[0].server="http://monitor.wifimedia.vn/api/monitoring/"
	commit wifimedia
EOF
}

NET_ID="hotspot"
FW_ZONE="hotspot"
IFNAME="eth0.300" #VLAN1
uci batch << EOF
	set network.${NET_ID}=interface
	set network.${NET_ID}.ifname=${IFNAME}
	set network.${NET_ID}.proto=static
	set network.${NET_ID}.type=bridge
	set network.${NET_ID}.ipaddr=10.68.255.1
	set network.${NET_ID}.netmask=255.255.255.0
	set dhcp.${NET_ID}=dhcp
	set dhcp.${NET_ID}.interface=${NET_ID}
	set dhcp.${NET_ID}.start=100
	set dhcp.${NET_ID}.leasetime=1h
	set dhcp.${NET_ID}.limit=150
	set firewall.${FW_ZONE}=zone
	set firewall.${FW_ZONE}.name=${FW_ZONE}
	set firewall.${FW_ZONE}.network=${NET_ID}
	set firewall.${FW_ZONE}.forward=ACCEPT
	set firewall.${FW_ZONE}.output=ACCEPT
	set firewall.${FW_ZONE}.input=ACCEPT 
	set firewall.${FW_ZONE}_fwd=forwarding
	set firewall.${FW_ZONE}_fwd.src=${FW_ZONE}
	set firewall.${FW_ZONE}_fwd.dest=wan
	set firewall.${FW_ZONE}_dhcp=rule
	set firewall.${FW_ZONE}_dhcp.name=${FW_ZONE}_DHCP
	set firewall.${FW_ZONE}_dhcp.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dhcp.target=ACCEPT
	set firewall.${FW_ZONE}_dhcp.proto=udp
	set firewall.${FW_ZONE}_dhcp.dest_port=67-68
	set firewall.${FW_ZONE}_dns=rule
	set firewall.${FW_ZONE}_dns.name=${FW_ZONE}_DNS
	set firewall.${FW_ZONE}_dns.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dns.target=ACCEPT
	set firewall.${FW_ZONE}_dns.proto=tcpudp
	set firewall.${FW_ZONE}_dns.dest_port=53
	set dhcp.${NET_ID}.force=1
	set dhcp.${NET_ID}.netmask=255.255.255.0
	add_list dhcp.${NET_ID}.dhcp_option=6,8.8.8.8,8.8.4.4
	commit firewall
	commit network
	commit dhcp
EOF

LTE_ZONE="4glte"
LTE_INT="lte"
uci batch << EOF
	set firewall.${LTE_ZONE}=zone
	set firewall.${LTE_ZONE}.input=ACCEPT
	set firewall.${LTE_ZONE}.forward=ACCEPT
	set firewall.${LTE_ZONE}.output=ACCEPT
	set firewall.${LTE_ZONE}.name=${LTE_INT}
	set firewall.${LTE_ZONE}.masq=1
	set firewall.${LTE_ZONE}.network=${LTE_INT}
	set firewall.${LTE_ZONE}_fwd_lan=forwarding
	set firewall.${LTE_ZONE}_fwd_lan.dest=lan
	set firewall.${LTE_ZONE}_fwd_lan.src=${LTE_INT}
	set firewall.${LTE_ZONE}_fwd_lte=forwarding
	set firewall.${LTE_ZONE}_fwd_lte.dest=${LTE_INT}
	set firewall.${LTE_ZONE}_fwd_lte.src=lan
	set firewall.${LTE_ZONE}_fwd_p=forwarding
	set firewall.${LTE_ZONE}_fwd_p.dest=${NET_ID}
	set firewall.${LTE_ZONE}_fwd_p.src=${LTE_INT}
	set firewall.${LTE_ZONE}_fwd_lte_p=forwarding
	set firewall.${LTE_ZONE}_fwd_lte_p.dest=${LTE_INT}
	set firewall.${LTE_ZONE}_fwd_lte_p.src=${NET_ID}
	commit firewall
EOF

touch /etc/opt/wfm_status
rm -f /etc/banner
mv /etc/banner_ /etc/banner
chmod +x /sbin/wifimedia/*
/etc/init.d/cron start
/etc/init.d/dropbear restart
/etc/init.d/network restart
/etc/init.d/network_reload enable
ifup lan
