#!/bin/sh

# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@mwan3[-1]
	add ucitrack mwan3
	set ucitrack.@mwan3[-1].exec="/etc/init.d/mwan3 reload"
	del mwan3.wan6
	del mwan3.wanb6
	del mwan3.wan6_m1_w3
	del mwan3.wan6_m2_w3
	del mwan3.wanb6_m1_w2
	del mwan3.wanb6_m2_w2
	commit ucitrack
	commit mwan3
EOF

uci -q get mwan3.globals >/dev/null || {
	uci -q add mwan3 globals >/dev/null
	uci -q rename mwan3.@globals[-1]="globals" >/dev/null
	uci -q set mwan3.globals.local_source="none" >/dev/null
	uci commit mwan3
}

# remove LuCI cache
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
